# Generated by Django 5.1 on 2025-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('Fazendo', 'Em progresso'), ('Feito', 'Completo')], max_length=9),
        ),
    ]
